name             'consul'
maintainer       'Denis Barishev'
maintainer_email 'dennybaa@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures consul'
long_description 'Installs/Configures consul'
version          '0.1.2'

depends 'fig'
depends 'selfpki'
depends 'runit'
depends 'apt'
